baseURL = "/"
languageCode = "fa-IR"
title = "Melad Kamari | میلاد کمری"
theme = "hyde-hyde"
disqusShortname = "Melad Kamari"
enableRobotsTXT = true
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
    themeColor="theme-base-melad"
    authorimage  = "/img/MeladKamari.jpeg"
    layoutReverse = false
    title = "Melad Kamari"
    description = "Software Architect"
    dateformat = "01/02/2006"
    highlightjs = true
    highlightjsstyle = "atom-one-dark"
     rtl=true
     copyright=true
     showBuiltWith=true
##Social Account
[params.social]
	twitter = "MeladKamari"
	github = "MeladKamari"
    email = "meladhamedani@gmail.com"
    linkedin = "melad-kamari-70a65b120/"
    medium = "meladkamari"
    telegram = "meladkamari"
##Main menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"



   