baseURL = "/"
languageCode = "fa-IR"
title = "MeladHamedani | میلاد همدانی"
theme = "hyde-hyde"
disqusShortname = "Melad Hamedani"
[params]
    authorimage  = "/img/MeladHamedani.jpeg"
    layoutReverse = false
    title = "Melad Hamedani"
    description = "Software Architecture"
    dateformat = "01/02/2006"
    highlightjs = true
    highlightjsstyle = "atom-one-dark"
##Social Account
[params.social]
	twitter = "MeladHamedani"
	github = "MeladHamedani"
    email = "meladhamedani@gmail.com"
    linkedin = "melad-hamedani-70a65b120/"
    medium = "meladhamedani"
    telegram = "meladhamedani"
##Main menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Articles"
    weight = 200
    identifier = "posts"
    url = "/"


   